# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5a99a8c79b9a22ebb2c92db111626b3179e70d2495d3345eccc4d49c9ec609265b968f56320c3952c283856f5f3e7ac575b5b8f453cbd2a239aebd0a64ab321

test:
  secret_key_base: 7012b125de5f857a456c9b22bce4507575ea75332bec59839ee38d1df5fac74fdbd8f36bd7353234ac2fbb89d33f771503d07ed7174835b3d60a49eaae5e4dab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
